[patricknix]
type = "nixos"
system = "x86_64-linux"

[desktopnix]
type = "nixos"
system = "x86_64-linux"

[testienix]
type = "nixos"
system = "x86_64-linux"

[gojo]
type = "nixos"
system = "x86_64-linux"

[maddy]
type = "nixos"
system = "x86_64-linux"
