#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

xset m 1 0
xsetroot -solid '#000000'
#
xset r rate 235 60

# copied from nixos wiki
# https://nixos.wiki/wiki/Using_X_without_a_Display_Manager
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval $(dbus-launch --exit-with-session --sh-syntax)
fi
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
        dbus-update-activation-environment DISPLAY XAUTHORITY
fi

autorandr -c
systemctl --user start set-wallpaper.service
exec i3
