#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# copied from nixos wiki
# https://nixos.wiki/wiki/Using_X_without_a_Display_Manager
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval $(dbus-launch --exit-with-session --sh-syntax)
fi
systemctl --user import-environment PATH DISPLAY XAUTHORITY XDG_CONFIG_DIRS XDG_DATA_DIRS XDG_RUNTIME_DIR XDG_SESSION_ID DBUS_SESSION_BUS_ADDRESS || true

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
        dbus-update-activation-environment --systemd --all
fi

# I3 does no start graphical session.target because ????
# so we need to manually start all service we want
xset r rate 235 60
exec i3
