#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

xrdb load "${HOME}/.Xresources"
xset m 1 0
#syndaemon -d -i 1.2 -t -K
xsetroot -solid '#000000'
#echo disabled > /sys/bus/usb/devices/1-1/power/wakeup
#
#touchegg &
#dunst &
exec dbus-launch --sh-syntax --exit-with-session -- herbstluftwm --locked
